### PR TITLE
Report screen

### PR DESCRIPTION
**Pull request by thuanvoit**
- fix notification disappear
- added report posts view
- fixed spacing between item in post
- added scrollview to images on posts to avoid overflow

Request:
```json
URL: /post/keepPost or /post/removePost
data: {
    communityId: post.communityId,
    postId: post.id,
    moderatorId: userId,
},
```

Response: status

### CODE REVIEW

**Review by doan1212 — APPROVED** [review]
The UI is very user-friendly

**Comment by thuanvoit** [comment]
Ready to merge!

**Review by nilrelyt — APPROVED** [review]
Looks nicee!

**Pull request merged**
