### PR TITLE
Create Notification screen with notification message UI

### PR DESCRIPTION
**Pull request by doan1212**
image

### CODE REVIEW

**Review by binayatimsina — APPROVED** [review]

**Review by thuanvoit — APPROVED** [review]
great job!

**Comment by thuanvoit** [comment]
Each Noti: 

```json
dateTime: '2021-10-10T00:00:00',
type: 'comment',
postId: '541',
userId: 'D',
communityId: '333',
userFullName: 'User F',
communityName: 'Community 22',
```

**Comment by thuanvoit** [comment]
Each Noti: 

```text
{
dateTime: '2021-10-10T00:00:00',
type: 'comment',  <-- display icon + background
postId: '541'. <-- open Post when press on noti
userId: 'D', <-- for Fullname process
communityId: '333', <-- open Post when press on noti
userFullName: 'User F',  <-- process in backend and set user full name
communityName: 'Community 22',  <-- process in backend and set community full name
}
```

**Review by thuanvoit — CHANGES_REQUESTED** [review]
looking for opinion on my changes

**Review by LordArjuna — APPROVED** [review]

**Review by thuanvoit — APPROVED** [review]

**Pull request merged**
