### PR TITLE
Add Moderator When Creating Community

### PR DESCRIPTION
**Pull request by nilrelyt**

### CODE REVIEW

**Review by doan1212 — APPROVED** [review]
Can you screenshot the result ?

**Comment by nilrelyt** [comment]
> Can you screenshot the result ?

oh my bad lemme add the screenshot

**Comment by nilrelyt** [comment]
Simulator Screenshot - iPhone 15 Pro Max - 2024-03-28 at 13 30 04

Simulator Screenshot - iPhone 15 Pro Max - 2024-03-28 at 13 30 14

**Review by binayatimsina — APPROVED** [review]
Great work Tyler

**Review by thuanvoit — CHANGES_REQUESTED** [review]
Great works! Wait for #45

**Review by thuanvoit — APPROVED** [review]
Great job!

**Pull request merged**
