### PR TITLE
Registration UI

### PR DESCRIPTION
**Pull request by binayatimsina**
image

### CODE REVIEW

**Comment by doan1212** [comment]
Look great, but can you change the button color, so it will match with our color scheme #523689 or #FFE79B

**Review by doan1212 — APPROVED** [review]

**Comment by doan1212** [comment]
image

**Comment by thuanvoit** [comment]
Please don't merge yet. We have 2 UI problem:
- not scrollable view
- dropdown menu is not usable (consider: https://github.com/react-native-menu/menu)
- fix some border input and color

**Review by thuanvoit — CHANGES_REQUESTED** [review]
Please don't merge yet. We have 2 UI problem:

not scrollable view
dropdown menu is not usable (consider: https://github.com/react-native-menu/menu)
fix some border input and color

**Review by thuanvoit — APPROVED** [review]
great!

**Pull request merged**
