### PR TITLE
Comments and Like number updates

### PR DESCRIPTION
**Pull request by binayatimsina**
image0 (5)
Added Comment class and included a example under the post class just to use as a references. There is also input field to put in comments but it is not correctly implemented fully. Whenever the comment icon is pressed, it will show the sample comments and input field for now!

### CODE REVIEW

**Review by thuanvoit — CHANGES_REQUESTED** [review]
I'm modifying the ui a little

**Comment by thuanvoit** [comment]
new comment design

**Review by thuanvoit — APPROVED** [review]

**Review by thuanvoit — CHANGES_REQUESTED** [review]
I will use this one to work on comment function

**Comment by thuanvoit** [comment]
Screenshot 2024-02-16 at 4 38 33 PM

**Review by doan1212 — APPROVED** [review]
Good Job

**Review by doan1212 — APPROVED** [review]
Good job

**Review by thuanvoit — APPROVED** [review]

**Pull request merged**
