### PR TITLE
Add home Page functionality

### PR DESCRIPTION
**Pull request by binayatimsina**
Added The Home Page Functionality. For now I created a method in the backend that returns all the avilable post. So the home page will show all the avilable post. However, it will only show the relevant post when the processed post are ready in the backend.

### CODE REVIEW

**Review by doan1212 — APPROVED** [review]
Great Job

**Review by nilrelyt — APPROVED** [review]
Nice work!

**Review by thuanvoit — CHANGES_REQUESTED** [review]
wait for #43

**Comment by thuanvoit** [comment]
Great works @binayatimsina !

**Comment by thuanvoit** [comment]
Ready to merge! Wait for #43

**Review by thuanvoit — APPROVED** [review]
Great job Binaya!

**Pull request merged**
